sudo: false
cache:
  directories:
    - $HOME/.m2
dist: trusty
language: java
jdk:
- oraclejdk8
os:
  - linux
script: mvn clean package
install: true
after_success:
  - "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ] && mvn -s ./deploy-settings.xml clean deploy"
